<a href="https://colab.research.google.com/github/satyamadhavarapu/Quantum-Machine-Learning/blob/main/task_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print("\n" + "="*50)
print("TASK 7: GROVER'S ORACLE (2-QUBIT)")
print("="*50)

def grover_oracle_2qubit(marked_state=3):
    oracle = np.eye(4)
    oracle[marked_state, marked_state] = -1
    return oracle

oracle_0 = grover_oracle_2qubit(0)
oracle_3 = grover_oracle_2qubit(3)

print("Oracle marking |00⟩:")
print(oracle_0)
print("\nOracle marking |11⟩:")
print(oracle_3)

uniform_superposition = np.ones(4) / 2

print(f"\nUniform superposition: {uniform_superposition}")
print(f"After oracle (|11⟩ marked): {oracle_3 @ uniform_superposition}")



TASK 7: GROVER'S ORACLE (2-QUBIT)
Oracle marking |00⟩:
[[-1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

Oracle marking |11⟩:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

Uniform superposition: [0.5 0.5 0.5 0.5]
After oracle (|11⟩ marked): [ 0.5  0.5  0.5 -0.5]
